set(mpc_args
--prefix=${CMAKE_INSTALL_PREFIX}
--with-gmp=${GMP_ROOT}
--with-mpfr=${MPFR_ROOT}
)

ExternalProject_Add(MPC
URL ${mpc_url}
CONFIGURE_COMMAND <SOURCE_DIR>/configure ${mpc_args} CFLAGS=${CMAKE_C_FLAGS} LDFLAGS=${LDFLAGS}
BUILD_COMMAND ${MAKE_EXECUTABLE} -j${NCPU}
INSTALL_COMMAND ${MAKE_EXECUTABLE} -j${NCPU} install
TEST_COMMAND ""
INACTIVITY_TIMEOUT 60
CONFIGURE_HANDLED_BY_BUILD ON
DEPENDS "GMP;MPFR"
)

cmake_path(SET MPC_ROOT ${CMAKE_INSTALL_PREFIX})
