if(find_gmp)
  find_path(GMP_INCLUDE_DIR NAMES gmp.h)
  if(GMP_INCLUDE_DIR)
    cmake_path(GET GMP_INCLUDE_DIR PARENT_PATH GMP_ROOT)
    add_custom_target(GMP)
  endif()
endif()
if(NOT GMP_ROOT)
  extproj(GMP ${gmp_url} "" "")
  set(GMP_ROOT ${CMAKE_INSTALL_PREFIX})
  message(STATUS "GMP: ${gmp_url}")
endif()
