if(find_gmp)
  find_path(GMP_INCLUDE_DIR NAMES gmp.h)
  if(GMP_INCLUDE_DIR)
    file(READ ${GMP_INCLUDE_DIR}/gmp.h gmp_h)
    string(REGEX MATCH "#define __GNU_MP_VERSION[ ]+([0-9]+)" _ ${gmp_h})
    set(GMP_VERSION_MAJOR ${CMAKE_MATCH_1})
    string(REGEX MATCH "#define __GNU_MP_VERSION_MINOR[ ]+([0-9]+)" _ ${gmp_h})
    set(GMP_VERSION_MINOR ${CMAKE_MATCH_1})
    string(REGEX MATCH "#define __GNU_MP_VERSION_PATCHLEVEL[ ]+([0-9]+)" _ ${gmp_h})
    set(GMP_VERSION_PATCHLEVEL ${CMAKE_MATCH_1})
    set(GMP_VERSION ${GMP_VERSION_MAJOR}.${GMP_VERSION_MINOR}.${GMP_VERSION_PATCHLEVEL})
    message(STATUS "Found GMP version ${GMP_VERSION}")
    cmake_path(GET GMP_INCLUDE_DIR PARENT_PATH GMP_ROOT)
    add_custom_target(GMP)
  endif()
endif()

if(NOT GMP_ROOT)
  extproj(GMP ${gmp_url} "" "")
  set(GMP_ROOT ${CMAKE_INSTALL_PREFIX})
  message(STATUS "GMP: ${gmp_url}")
endif()
