if(isl)
  if(find_isl)
    find_path(ISL_INCLUDE_DIR NAMES isl/ctx.h)
    if(ISL_INCLUDE_DIR)
      cmake_path(GET ISL_INCLUDE_DIR PARENT_PATH ISL_ROOT)
      add_custom_target(ISL)
    endif()
  endif()
  if(NOT ISL_ROOT)
    extproj(ISL ${isl_url} "--with-gmp-prefix=${GMP_ROOT}" "GMP")
    set(ISL_ROOT ${CMAKE_INSTALL_PREFIX})
  endif()
else()
  add_custom_target(ISL)
endif()
