if(find_mpfr)
  find_path(MPFR_INCLUDE_DIR NAMES mpfr.h)
  if(MPFR_INCLUDE_DIR)
    file(READ ${MPFR_INCLUDE_DIR}/mpfr.h mpfr_h)
    string(REGEX MATCH "#define MPFR_VERSION_MAJOR ([0-9]+)" _ ${mpfr_h})
    set(MPFR_VERSION_MAJOR ${CMAKE_MATCH_1})
    string(REGEX MATCH "#define MPFR_VERSION_MINOR ([0-9]+)" _ ${mpfr_h})
    set(MPFR_VERSION_MINOR ${CMAKE_MATCH_1})
    set(MPFR_VERSION ${MPFR_VERSION_MAJOR}.${MPFR_VERSION_MINOR})
    message(STATUS "Found MPFR version ${MPFR_VERSION}")
    if(MPFR_VERSION VERSION_LESS 4.1)
      unset(MPFR_INCLUDE_DIR CACHE)
    else()
      cmake_path(GET MPFR_INCLUDE_DIR PARENT_PATH MPFR_ROOT)
      add_custom_target(MPFR)
    endif()
  endif()
endif()

if(NOT MPFR_ROOT)
  extproj(MPFR ${mpfr_url} "--with-gmp=${GMP_ROOT}" "GMP")
  set(MPFR_ROOT ${CMAKE_INSTALL_PREFIX})
  message(STATUS "MPFR: ${mpfr_url}")
endif()
