if(NOT zstd)
  add_custom_target(ZSTD)
  return()
endif()

set(zstd_cmake_args
-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
-DBUILD_TESTING:BOOL=false
-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
)

ExternalProject_Add(ZSTD
URL ${zstd_url}
SOURCE_SUBDIR build/cmake
CMAKE_ARGS ${zstd_cmake_args}
TEST_COMMAND ""
USES_TERMINAL_DOWNLOAD true
USES_TERMINAL_UPDATE true
USES_TERMINAL_PATCH true
USES_TERMINAL_CONFIGURE true
USES_TERMINAL_BUILD true
USES_TERMINAL_INSTALL true
USES_TERMINAL_TEST true
)

set(ZSTD_ROOT ${CMAKE_INSTALL_PREFIX})
